# Numpy Cheat Sheet 
<hr>

In [1]:
import numpy as np #импорт, подключение библиотеки

In [7]:
data=[1,2,3,4,5,6,7,8]
array=np.array(data) # создали одномерный массив и запихнули в него данные
print(array)
array.shape #шейп массива
array.dtype #тип элементов

[1 2 3 4 5 6 7 8]


dtype('int32')

Типы данных NUMPY int64,int32,float32,float64,complex,bool,obj,str,unicode

In [15]:
array.dtype
array2=np.array(data,dtype=np.float64) #преобразование типов данных
array2.dtype

dtype('float64')

ПОТЕРЯ ДАННЫХ

In [19]:
data2=[1,2,129,256]
array3=np.array(data2)
print(array3)
array3=np.array(data2,dtype=np.int8)  
print(array3)

[  1   2 129 256]
[   1    2 -127    0]


In [23]:
print(len(array3)) #Длина массива
print('size',array3.size) #Размер масссива

4
size 4


Приведение элементов массива к типу

In [26]:
array3=array3.astype(np.int32)
print(array3)
array3.dtype

[   1    2 -127    0]


dtype('int32')

In [39]:
array4=np.arange(1.0,10.0,1.5) #Заполнение массива (Start,Stop,Step)
print(array4.dtype)
print(array4)
array5=np.linspace(1,10,10) #Заполнение массива (Start,Stop,Count)
print(array5)

float64
[1.  2.5 4.  5.5 7.  8.5]
[ 1  2  3  4  5  6  7  8  9 10]


In [58]:
array6=np.random.random_sample(6) #Рандомные 6 значений
array7=np.random.random(7)
array8=np.random.random_integers(1,10,7) #Рандомные 7 значений в диапазоне от 1 до 10
array9=np.random.randn() #Рандомные float числа

C:\Users\vpesp\AppData\Local\Temp\ipykernel_12772\3895639849.py:3: DeprecationWarning: This function is deprecated. Please call randint(1, 10 + 1) instead
  array8=np.random.random_integers(1,10,7) #Рандомные 7 значений в диапазоне от 1 до 10


-1.828895332311456

Математические функции

In [66]:
array10=np.array([4,16,64])
array10=np.sqrt(array10) #Корень квадратный
array10=np.log(array10) #Логарифм
array10=np.cos(array4) #Косинус
array10=np.exp(array4) #Экспонента
array10

array([2.71828183e+00, 1.21824940e+01, 5.45981500e+01, 2.44691932e+02,
       1.09663316e+03, 4.91476884e+03])

Операции с массивами

In [116]:
array11=np.array([1,2,3])
array12=np.array([1,2,3])
np.add(array11,array12) #Сложение
np.subtract(array11,array12) #Вычитание , а еще есть np.divide, np.multiply
np.min(array11)
np.max(array11)
np.mean(array11)
np.sum(array11)
np.std(array11)
np.median(array11)

2.0

In [117]:
array11==2 #Условия для элементов массива

array([False,  True, False])

In [119]:
array11=np.insert(array11,2,88)
array11
#array11=np.delete(array11,2)
array11

array([ 1,  2, 88, 88,  3])

In [146]:

array13=np.random.random_integers(1,10,7)
array13=np.sort(array13) #Сортировка
array16=np.array([0,0,0]).astype(np.int32)
array17=np.array([1,2,3,4,5,6]).astype(np.int32)
array18=np.array_split(array17,3)




[1 2 3 4 5 6]


C:\Users\vpesp\AppData\Local\Temp\ipykernel_12772\2250085311.py:1: DeprecationWarning: This function is deprecated. Please call randint(1, 10 + 1) instead
  array13=np.random.random_integers(1,10,7)


In [149]:
array19=np.array([1,2,3,4,5,6])
print(array19[2:4])

[3 4]


МНОГОМЕРНЫЕ МАССИВЫ

In [174]:
array20=np.array([[1,2,3,4],[1,2,3,4],[1,2,3,4]])
np.max(array20,axis=0)
a = [[1, 2, 3, 4], [5,6,7,8], [7, 8, 9]]
for i in range(len(a)):
    for j in range(len(a[i])):
        print(a[i][j], end=' ')
    print()



1 2 3 4 
5 6 
7 8 9 
